// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcjjvxzooszhkekemwno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpjamp2eHpvb3N6aGtla2Vtd25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzMTMyNjIsImV4cCI6MjA3OTg4OTI2Mn0.8TeaygqdadbI3I7rnkI64_4-k2zvrizun7ehx2nU-hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});